# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from main2021/position.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class position(genpy.Message):
  _md5sum = "04836b89de39e862e20e94175e8fc855"
  _type = "main2021/position"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 my_x
float32 my_y
float32 my_z
float32 my_degreex
float32 my_degreey
float32 my_degreez
float32 my_degreew
"""
  __slots__ = ['my_x','my_y','my_z','my_degreex','my_degreey','my_degreez','my_degreew']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       my_x,my_y,my_z,my_degreex,my_degreey,my_degreez,my_degreew

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(position, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.my_x is None:
        self.my_x = 0.
      if self.my_y is None:
        self.my_y = 0.
      if self.my_z is None:
        self.my_z = 0.
      if self.my_degreex is None:
        self.my_degreex = 0.
      if self.my_degreey is None:
        self.my_degreey = 0.
      if self.my_degreez is None:
        self.my_degreez = 0.
      if self.my_degreew is None:
        self.my_degreew = 0.
    else:
      self.my_x = 0.
      self.my_y = 0.
      self.my_z = 0.
      self.my_degreex = 0.
      self.my_degreey = 0.
      self.my_degreez = 0.
      self.my_degreew = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.my_x, _x.my_y, _x.my_z, _x.my_degreex, _x.my_degreey, _x.my_degreez, _x.my_degreew))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.my_x, _x.my_y, _x.my_z, _x.my_degreex, _x.my_degreey, _x.my_degreez, _x.my_degreew,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.my_x, _x.my_y, _x.my_z, _x.my_degreex, _x.my_degreey, _x.my_degreez, _x.my_degreew))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.my_x, _x.my_y, _x.my_z, _x.my_degreex, _x.my_degreey, _x.my_degreez, _x.my_degreew,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
