(cl:in-package main2021-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          FX-VAL
          FX
          FY-VAL
          FY
          DEGREE-VAL
          DEGREE
          ACTION-VAL
          ACTION
          ACTION_LIST-VAL
          ACTION_LIST
          CUP_COLOR-VAL
          CUP_COLOR
          CUP-VAL
          CUP
          SCRIPT-VAL
          SCRIPT
          NS-VAL
          NS
          TEAM-VAL
          TEAM
          TIME-VAL
          TIME
          STATUS-VAL
          STATUS
))