// Generated by gencpp from file main2021/cup.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_CUP_H
#define MAIN2021_MESSAGE_CUP_H

#include <ros/service_traits.h>


#include <main2021/cupRequest.h>
#include <main2021/cupResponse.h>


namespace main2021
{

struct cup
{

typedef cupRequest Request;
typedef cupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cup
} // namespace main2021


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main2021::cup > {
  static const char* value()
  {
    return "1ba64ca04594ee6db0df538fffb0ec78";
  }

  static const char* value(const ::main2021::cup&) { return value(); }
};

template<>
struct DataType< ::main2021::cup > {
  static const char* value()
  {
    return "main2021/cup";
  }

  static const char* value(const ::main2021::cup&) { return value(); }
};


// service_traits::MD5Sum< ::main2021::cupRequest> should match
// service_traits::MD5Sum< ::main2021::cup >
template<>
struct MD5Sum< ::main2021::cupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::cup >::value();
  }
  static const char* value(const ::main2021::cupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::cupRequest> should match
// service_traits::DataType< ::main2021::cup >
template<>
struct DataType< ::main2021::cupRequest>
{
  static const char* value()
  {
    return DataType< ::main2021::cup >::value();
  }
  static const char* value(const ::main2021::cupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main2021::cupResponse> should match
// service_traits::MD5Sum< ::main2021::cup >
template<>
struct MD5Sum< ::main2021::cupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::cup >::value();
  }
  static const char* value(const ::main2021::cupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::cupResponse> should match
// service_traits::DataType< ::main2021::cup >
template<>
struct DataType< ::main2021::cupResponse>
{
  static const char* value()
  {
    return DataType< ::main2021::cup >::value();
  }
  static const char* value(const ::main2021::cupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN2021_MESSAGE_CUP_H
