// Generated by gencpp from file main2021/cup_camera.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_CUP_CAMERA_H
#define MAIN2021_MESSAGE_CUP_CAMERA_H

#include <ros/service_traits.h>


#include <main2021/cup_cameraRequest.h>
#include <main2021/cup_cameraResponse.h>


namespace main2021
{

struct cup_camera
{

typedef cup_cameraRequest Request;
typedef cup_cameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cup_camera
} // namespace main2021


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main2021::cup_camera > {
  static const char* value()
  {
    return "7a20991e451c1198c7723ab0b4776fd9";
  }

  static const char* value(const ::main2021::cup_camera&) { return value(); }
};

template<>
struct DataType< ::main2021::cup_camera > {
  static const char* value()
  {
    return "main2021/cup_camera";
  }

  static const char* value(const ::main2021::cup_camera&) { return value(); }
};


// service_traits::MD5Sum< ::main2021::cup_cameraRequest> should match
// service_traits::MD5Sum< ::main2021::cup_camera >
template<>
struct MD5Sum< ::main2021::cup_cameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::cup_camera >::value();
  }
  static const char* value(const ::main2021::cup_cameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::cup_cameraRequest> should match
// service_traits::DataType< ::main2021::cup_camera >
template<>
struct DataType< ::main2021::cup_cameraRequest>
{
  static const char* value()
  {
    return DataType< ::main2021::cup_camera >::value();
  }
  static const char* value(const ::main2021::cup_cameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main2021::cup_cameraResponse> should match
// service_traits::MD5Sum< ::main2021::cup_camera >
template<>
struct MD5Sum< ::main2021::cup_cameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::cup_camera >::value();
  }
  static const char* value(const ::main2021::cup_cameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::cup_cameraResponse> should match
// service_traits::DataType< ::main2021::cup_camera >
template<>
struct DataType< ::main2021::cup_cameraResponse>
{
  static const char* value()
  {
    return DataType< ::main2021::cup_camera >::value();
  }
  static const char* value(const ::main2021::cup_cameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN2021_MESSAGE_CUP_CAMERA_H
