// Generated by gencpp from file main2021/goap_srv.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_GOAP_SRV_H
#define MAIN2021_MESSAGE_GOAP_SRV_H

#include <ros/service_traits.h>


#include <main2021/goap_srvRequest.h>
#include <main2021/goap_srvResponse.h>


namespace main2021
{

struct goap_srv
{

typedef goap_srvRequest Request;
typedef goap_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goap_srv
} // namespace main2021


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main2021::goap_srv > {
  static const char* value()
  {
    return "93ddba8ccf100824f0cb0d18004bda97";
  }

  static const char* value(const ::main2021::goap_srv&) { return value(); }
};

template<>
struct DataType< ::main2021::goap_srv > {
  static const char* value()
  {
    return "main2021/goap_srv";
  }

  static const char* value(const ::main2021::goap_srv&) { return value(); }
};


// service_traits::MD5Sum< ::main2021::goap_srvRequest> should match
// service_traits::MD5Sum< ::main2021::goap_srv >
template<>
struct MD5Sum< ::main2021::goap_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::goap_srv >::value();
  }
  static const char* value(const ::main2021::goap_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::goap_srvRequest> should match
// service_traits::DataType< ::main2021::goap_srv >
template<>
struct DataType< ::main2021::goap_srvRequest>
{
  static const char* value()
  {
    return DataType< ::main2021::goap_srv >::value();
  }
  static const char* value(const ::main2021::goap_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main2021::goap_srvResponse> should match
// service_traits::MD5Sum< ::main2021::goap_srv >
template<>
struct MD5Sum< ::main2021::goap_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::goap_srv >::value();
  }
  static const char* value(const ::main2021::goap_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::goap_srvResponse> should match
// service_traits::DataType< ::main2021::goap_srv >
template<>
struct DataType< ::main2021::goap_srvResponse>
{
  static const char* value()
  {
    return DataType< ::main2021::goap_srv >::value();
  }
  static const char* value(const ::main2021::goap_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN2021_MESSAGE_GOAP_SRV_H
