// Generated by gencpp from file main2021/maintomission.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_MAINTOMISSION_H
#define MAIN2021_MESSAGE_MAINTOMISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main2021
{
template <class ContainerAllocator>
struct maintomission_
{
  typedef maintomission_<ContainerAllocator> Type;

  maintomission_()
    : team(0)
    , action(0)
    , planer_state(0)
    , action_pos()
    , cup()
    , hand()
    , reef()
    , NS(false)
    , emerg(false)  {
    }
  maintomission_(const ContainerAllocator& _alloc)
    : team(0)
    , action(0)
    , planer_state(0)
    , action_pos(_alloc)
    , cup(_alloc)
    , hand(_alloc)
    , reef(_alloc)
    , NS(false)
    , emerg(false)  {
  (void)_alloc;
    }



   typedef int32_t _team_type;
  _team_type team;

   typedef int32_t _action_type;
  _action_type action;

   typedef int32_t _planer_state_type;
  _planer_state_type planer_state;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _action_pos_type;
  _action_pos_type action_pos;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _cup_type;
  _cup_type cup;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _hand_type;
  _hand_type hand;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _reef_type;
  _reef_type reef;

   typedef uint8_t _NS_type;
  _NS_type NS;

   typedef uint8_t _emerg_type;
  _emerg_type emerg;





  typedef boost::shared_ptr< ::main2021::maintomission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main2021::maintomission_<ContainerAllocator> const> ConstPtr;

}; // struct maintomission_

typedef ::main2021::maintomission_<std::allocator<void> > maintomission;

typedef boost::shared_ptr< ::main2021::maintomission > maintomissionPtr;
typedef boost::shared_ptr< ::main2021::maintomission const> maintomissionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main2021::maintomission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main2021::maintomission_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main2021::maintomission_<ContainerAllocator1> & lhs, const ::main2021::maintomission_<ContainerAllocator2> & rhs)
{
  return lhs.team == rhs.team &&
    lhs.action == rhs.action &&
    lhs.planer_state == rhs.planer_state &&
    lhs.action_pos == rhs.action_pos &&
    lhs.cup == rhs.cup &&
    lhs.hand == rhs.hand &&
    lhs.reef == rhs.reef &&
    lhs.NS == rhs.NS &&
    lhs.emerg == rhs.emerg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main2021::maintomission_<ContainerAllocator1> & lhs, const ::main2021::maintomission_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main2021

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main2021::maintomission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main2021::maintomission_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::maintomission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::maintomission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::maintomission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::maintomission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main2021::maintomission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6c4bebd0fdd628f3d960dc0cc16a1cf";
  }

  static const char* value(const ::main2021::maintomission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6c4bebd0fdd628fULL;
  static const uint64_t static_value2 = 0x3d960dc0cc16a1cfULL;
};

template<class ContainerAllocator>
struct DataType< ::main2021::maintomission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main2021/maintomission";
  }

  static const char* value(const ::main2021::maintomission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main2021::maintomission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 team\n"
"int32 action\n"
"int32 planer_state\n"
"float32[] action_pos\n"
"int32[] cup\n"
"int32[] hand\n"
"int32[] reef\n"
"bool NS\n"
"bool emerg\n"
;
  }

  static const char* value(const ::main2021::maintomission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main2021::maintomission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.team);
      stream.next(m.action);
      stream.next(m.planer_state);
      stream.next(m.action_pos);
      stream.next(m.cup);
      stream.next(m.hand);
      stream.next(m.reef);
      stream.next(m.NS);
      stream.next(m.emerg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct maintomission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main2021::maintomission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main2021::maintomission_<ContainerAllocator>& v)
  {
    s << indent << "team: ";
    Printer<int32_t>::stream(s, indent + "  ", v.team);
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
    s << indent << "planer_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.planer_state);
    s << indent << "action_pos[]" << std::endl;
    for (size_t i = 0; i < v.action_pos.size(); ++i)
    {
      s << indent << "  action_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.action_pos[i]);
    }
    s << indent << "cup[]" << std::endl;
    for (size_t i = 0; i < v.cup.size(); ++i)
    {
      s << indent << "  cup[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.cup[i]);
    }
    s << indent << "hand[]" << std::endl;
    for (size_t i = 0; i < v.hand.size(); ++i)
    {
      s << indent << "  hand[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.hand[i]);
    }
    s << indent << "reef[]" << std::endl;
    for (size_t i = 0; i < v.reef.size(); ++i)
    {
      s << indent << "  reef[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.reef[i]);
    }
    s << indent << "NS: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.NS);
    s << indent << "emerg: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emerg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN2021_MESSAGE_MAINTOMISSION_H
