// Generated by gencpp from file main2021/mission_srv.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_MISSION_SRV_H
#define MAIN2021_MESSAGE_MISSION_SRV_H

#include <ros/service_traits.h>


#include <main2021/mission_srvRequest.h>
#include <main2021/mission_srvResponse.h>


namespace main2021
{

struct mission_srv
{

typedef mission_srvRequest Request;
typedef mission_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mission_srv
} // namespace main2021


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::main2021::mission_srv > {
  static const char* value()
  {
    return "bce17d4b6829904ca26b97013468df60";
  }

  static const char* value(const ::main2021::mission_srv&) { return value(); }
};

template<>
struct DataType< ::main2021::mission_srv > {
  static const char* value()
  {
    return "main2021/mission_srv";
  }

  static const char* value(const ::main2021::mission_srv&) { return value(); }
};


// service_traits::MD5Sum< ::main2021::mission_srvRequest> should match
// service_traits::MD5Sum< ::main2021::mission_srv >
template<>
struct MD5Sum< ::main2021::mission_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::mission_srv >::value();
  }
  static const char* value(const ::main2021::mission_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::mission_srvRequest> should match
// service_traits::DataType< ::main2021::mission_srv >
template<>
struct DataType< ::main2021::mission_srvRequest>
{
  static const char* value()
  {
    return DataType< ::main2021::mission_srv >::value();
  }
  static const char* value(const ::main2021::mission_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::main2021::mission_srvResponse> should match
// service_traits::MD5Sum< ::main2021::mission_srv >
template<>
struct MD5Sum< ::main2021::mission_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::main2021::mission_srv >::value();
  }
  static const char* value(const ::main2021::mission_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::main2021::mission_srvResponse> should match
// service_traits::DataType< ::main2021::mission_srv >
template<>
struct DataType< ::main2021::mission_srvResponse>
{
  static const char* value()
  {
    return DataType< ::main2021::mission_srv >::value();
  }
  static const char* value(const ::main2021::mission_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAIN2021_MESSAGE_MISSION_SRV_H
