// Generated by gencpp from file main2021/mission_srvResponse.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_MISSION_SRVRESPONSE_H
#define MAIN2021_MESSAGE_MISSION_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main2021
{
template <class ContainerAllocator>
struct mission_srvResponse_
{
  typedef mission_srvResponse_<ContainerAllocator> Type;

  mission_srvResponse_()
    : state(0)  {
    }
  mission_srvResponse_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int32_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::main2021::mission_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main2021::mission_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct mission_srvResponse_

typedef ::main2021::mission_srvResponse_<std::allocator<void> > mission_srvResponse;

typedef boost::shared_ptr< ::main2021::mission_srvResponse > mission_srvResponsePtr;
typedef boost::shared_ptr< ::main2021::mission_srvResponse const> mission_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main2021::mission_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main2021::mission_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main2021::mission_srvResponse_<ContainerAllocator1> & lhs, const ::main2021::mission_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main2021::mission_srvResponse_<ContainerAllocator1> & lhs, const ::main2021::mission_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main2021

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main2021::mission_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main2021::mission_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::mission_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::mission_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::mission_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::mission_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main2021::mission_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a2f37ef2ba405f0c7a15cc72663d6f0";
  }

  static const char* value(const ::main2021::mission_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a2f37ef2ba405f0ULL;
  static const uint64_t static_value2 = 0xc7a15cc72663d6f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::main2021::mission_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main2021/mission_srvResponse";
  }

  static const char* value(const ::main2021::mission_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main2021::mission_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 state\n"
"\n"
"\n"
;
  }

  static const char* value(const ::main2021::mission_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main2021::mission_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mission_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main2021::mission_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main2021::mission_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN2021_MESSAGE_MISSION_SRVRESPONSE_H
