// Generated by gencpp from file main2021/mission_srvRequest.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_MISSION_SRVREQUEST_H
#define MAIN2021_MESSAGE_MISSION_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main2021
{
template <class ContainerAllocator>
struct mission_srvRequest_
{
  typedef mission_srvRequest_<ContainerAllocator> Type;

  mission_srvRequest_()
    : action(0)
    , action_pos()
    , cup()
    , hand()  {
    }
  mission_srvRequest_(const ContainerAllocator& _alloc)
    : action(0)
    , action_pos(_alloc)
    , cup(_alloc)
    , hand(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _action_type;
  _action_type action;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _action_pos_type;
  _action_pos_type action_pos;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _cup_type;
  _cup_type cup;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _hand_type;
  _hand_type hand;





  typedef boost::shared_ptr< ::main2021::mission_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main2021::mission_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mission_srvRequest_

typedef ::main2021::mission_srvRequest_<std::allocator<void> > mission_srvRequest;

typedef boost::shared_ptr< ::main2021::mission_srvRequest > mission_srvRequestPtr;
typedef boost::shared_ptr< ::main2021::mission_srvRequest const> mission_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main2021::mission_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main2021::mission_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main2021::mission_srvRequest_<ContainerAllocator1> & lhs, const ::main2021::mission_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action &&
    lhs.action_pos == rhs.action_pos &&
    lhs.cup == rhs.cup &&
    lhs.hand == rhs.hand;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main2021::mission_srvRequest_<ContainerAllocator1> & lhs, const ::main2021::mission_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main2021

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main2021::mission_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main2021::mission_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::mission_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::mission_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::mission_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::mission_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main2021::mission_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81c9eb2b658b4c187113ebd56c6d5cec";
  }

  static const char* value(const ::main2021::mission_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81c9eb2b658b4c18ULL;
  static const uint64_t static_value2 = 0x7113ebd56c6d5cecULL;
};

template<class ContainerAllocator>
struct DataType< ::main2021::mission_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main2021/mission_srvRequest";
  }

  static const char* value(const ::main2021::mission_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main2021::mission_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 action\n"
"float32[] action_pos\n"
"int32[] cup\n"
"int32[] hand\n"
;
  }

  static const char* value(const ::main2021::mission_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main2021::mission_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.action_pos);
      stream.next(m.cup);
      stream.next(m.hand);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mission_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main2021::mission_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main2021::mission_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<int32_t>::stream(s, indent + "  ", v.action);
    s << indent << "action_pos[]" << std::endl;
    for (size_t i = 0; i < v.action_pos.size(); ++i)
    {
      s << indent << "  action_pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.action_pos[i]);
    }
    s << indent << "cup[]" << std::endl;
    for (size_t i = 0; i < v.cup.size(); ++i)
    {
      s << indent << "  cup[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.cup[i]);
    }
    s << indent << "hand[]" << std::endl;
    for (size_t i = 0; i < v.hand.size(); ++i)
    {
      s << indent << "  hand[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.hand[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN2021_MESSAGE_MISSION_SRVREQUEST_H
