// Generated by gencpp from file main2021/nsResponse.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_NSRESPONSE_H
#define MAIN2021_MESSAGE_NSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main2021
{
template <class ContainerAllocator>
struct nsResponse_
{
  typedef nsResponse_<ContainerAllocator> Type;

  nsResponse_()
    : ns_result(0)  {
    }
  nsResponse_(const ContainerAllocator& _alloc)
    : ns_result(0)  {
  (void)_alloc;
    }



   typedef int32_t _ns_result_type;
  _ns_result_type ns_result;





  typedef boost::shared_ptr< ::main2021::nsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main2021::nsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct nsResponse_

typedef ::main2021::nsResponse_<std::allocator<void> > nsResponse;

typedef boost::shared_ptr< ::main2021::nsResponse > nsResponsePtr;
typedef boost::shared_ptr< ::main2021::nsResponse const> nsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main2021::nsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main2021::nsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main2021::nsResponse_<ContainerAllocator1> & lhs, const ::main2021::nsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ns_result == rhs.ns_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main2021::nsResponse_<ContainerAllocator1> & lhs, const ::main2021::nsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main2021

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main2021::nsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main2021::nsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::nsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::nsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::nsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::nsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main2021::nsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2ad2f67474bb9a8e84b2525b4dadf8c";
  }

  static const char* value(const ::main2021::nsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2ad2f67474bb9a8ULL;
  static const uint64_t static_value2 = 0xe84b2525b4dadf8cULL;
};

template<class ContainerAllocator>
struct DataType< ::main2021::nsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main2021/nsResponse";
  }

  static const char* value(const ::main2021::nsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main2021::nsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ns_result\n"
"\n"
;
  }

  static const char* value(const ::main2021::nsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main2021::nsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ns_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main2021::nsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main2021::nsResponse_<ContainerAllocator>& v)
  {
    s << indent << "ns_result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ns_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN2021_MESSAGE_NSRESPONSE_H
