// Generated by gencpp from file main2021/nsRequest.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_NSREQUEST_H
#define MAIN2021_MESSAGE_NSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main2021
{
template <class ContainerAllocator>
struct nsRequest_
{
  typedef nsRequest_<ContainerAllocator> Type;

  nsRequest_()
    : ask_ns(0)  {
    }
  nsRequest_(const ContainerAllocator& _alloc)
    : ask_ns(0)  {
  (void)_alloc;
    }



   typedef int32_t _ask_ns_type;
  _ask_ns_type ask_ns;





  typedef boost::shared_ptr< ::main2021::nsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main2021::nsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nsRequest_

typedef ::main2021::nsRequest_<std::allocator<void> > nsRequest;

typedef boost::shared_ptr< ::main2021::nsRequest > nsRequestPtr;
typedef boost::shared_ptr< ::main2021::nsRequest const> nsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main2021::nsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main2021::nsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main2021::nsRequest_<ContainerAllocator1> & lhs, const ::main2021::nsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ask_ns == rhs.ask_ns;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main2021::nsRequest_<ContainerAllocator1> & lhs, const ::main2021::nsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main2021

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main2021::nsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main2021::nsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::nsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::nsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::nsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::nsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main2021::nsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a6b1691ab5ec180f4125d5a3869ba886";
  }

  static const char* value(const ::main2021::nsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa6b1691ab5ec180fULL;
  static const uint64_t static_value2 = 0x4125d5a3869ba886ULL;
};

template<class ContainerAllocator>
struct DataType< ::main2021::nsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main2021/nsRequest";
  }

  static const char* value(const ::main2021::nsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main2021::nsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ask_ns\n"
;
  }

  static const char* value(const ::main2021::nsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main2021::nsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ask_ns);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main2021::nsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main2021::nsRequest_<ContainerAllocator>& v)
  {
    s << indent << "ask_ns: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ask_ns);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN2021_MESSAGE_NSREQUEST_H
