// Generated by gencpp from file main2021/plannerState.msg
// DO NOT EDIT!


#ifndef MAIN2021_MESSAGE_PLANNERSTATE_H
#define MAIN2021_MESSAGE_PLANNERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main2021
{
template <class ContainerAllocator>
struct plannerState_
{
  typedef plannerState_<ContainerAllocator> Type;

  plannerState_()
    : plan_state()  {
    }
  plannerState_(const ContainerAllocator& _alloc)
    : plan_state(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _plan_state_type;
  _plan_state_type plan_state;





  typedef boost::shared_ptr< ::main2021::plannerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main2021::plannerState_<ContainerAllocator> const> ConstPtr;

}; // struct plannerState_

typedef ::main2021::plannerState_<std::allocator<void> > plannerState;

typedef boost::shared_ptr< ::main2021::plannerState > plannerStatePtr;
typedef boost::shared_ptr< ::main2021::plannerState const> plannerStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main2021::plannerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main2021::plannerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main2021::plannerState_<ContainerAllocator1> & lhs, const ::main2021::plannerState_<ContainerAllocator2> & rhs)
{
  return lhs.plan_state == rhs.plan_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main2021::plannerState_<ContainerAllocator1> & lhs, const ::main2021::plannerState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main2021

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main2021::plannerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main2021::plannerState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::plannerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main2021::plannerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::plannerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main2021::plannerState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main2021::plannerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f66f0959567ef2a880883da8a8aff308";
  }

  static const char* value(const ::main2021::plannerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf66f0959567ef2a8ULL;
  static const uint64_t static_value2 = 0x80883da8a8aff308ULL;
};

template<class ContainerAllocator>
struct DataType< ::main2021::plannerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main2021/plannerState";
  }

  static const char* value(const ::main2021::plannerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main2021::plannerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] plan_state\n"
"\n"
;
  }

  static const char* value(const ::main2021::plannerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main2021::plannerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.plan_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct plannerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main2021::plannerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main2021::plannerState_<ContainerAllocator>& v)
  {
    s << indent << "plan_state[]" << std::endl;
    for (size_t i = 0; i < v.plan_state.size(); ++i)
    {
      s << indent << "  plan_state[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.plan_state[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN2021_MESSAGE_PLANNERSTATE_H
