// Generated by gencpp from file aruco_pose/ns.msg
// DO NOT EDIT!


#ifndef ARUCO_POSE_MESSAGE_NS_H
#define ARUCO_POSE_MESSAGE_NS_H

#include <ros/service_traits.h>


#include <aruco_pose/nsRequest.h>
#include <aruco_pose/nsResponse.h>


namespace aruco_pose
{

struct ns
{

typedef nsRequest Request;
typedef nsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ns
} // namespace aruco_pose


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aruco_pose::ns > {
  static const char* value()
  {
    return "6db1d56b21aeaaf74af61c1e66674fb6";
  }

  static const char* value(const ::aruco_pose::ns&) { return value(); }
};

template<>
struct DataType< ::aruco_pose::ns > {
  static const char* value()
  {
    return "aruco_pose/ns";
  }

  static const char* value(const ::aruco_pose::ns&) { return value(); }
};


// service_traits::MD5Sum< ::aruco_pose::nsRequest> should match
// service_traits::MD5Sum< ::aruco_pose::ns >
template<>
struct MD5Sum< ::aruco_pose::nsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_pose::ns >::value();
  }
  static const char* value(const ::aruco_pose::nsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_pose::nsRequest> should match
// service_traits::DataType< ::aruco_pose::ns >
template<>
struct DataType< ::aruco_pose::nsRequest>
{
  static const char* value()
  {
    return DataType< ::aruco_pose::ns >::value();
  }
  static const char* value(const ::aruco_pose::nsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aruco_pose::nsResponse> should match
// service_traits::MD5Sum< ::aruco_pose::ns >
template<>
struct MD5Sum< ::aruco_pose::nsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_pose::ns >::value();
  }
  static const char* value(const ::aruco_pose::nsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_pose::nsResponse> should match
// service_traits::DataType< ::aruco_pose::ns >
template<>
struct DataType< ::aruco_pose::nsResponse>
{
  static const char* value()
  {
    return DataType< ::aruco_pose::ns >::value();
  }
  static const char* value(const ::aruco_pose::nsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARUCO_POSE_MESSAGE_NS_H
