// Generated by gencpp from file mission/mission_camera.msg
// DO NOT EDIT!


#ifndef MISSION_MESSAGE_MISSION_CAMERA_H
#define MISSION_MESSAGE_MISSION_CAMERA_H

#include <ros/service_traits.h>


#include <mission/mission_cameraRequest.h>
#include <mission/mission_cameraResponse.h>


namespace mission
{

struct mission_camera
{

typedef mission_cameraRequest Request;
typedef mission_cameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mission_camera
} // namespace mission


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mission::mission_camera > {
  static const char* value()
  {
    return "21a18da0693a50b6cde67125054bddd4";
  }

  static const char* value(const ::mission::mission_camera&) { return value(); }
};

template<>
struct DataType< ::mission::mission_camera > {
  static const char* value()
  {
    return "mission/mission_camera";
  }

  static const char* value(const ::mission::mission_camera&) { return value(); }
};


// service_traits::MD5Sum< ::mission::mission_cameraRequest> should match
// service_traits::MD5Sum< ::mission::mission_camera >
template<>
struct MD5Sum< ::mission::mission_cameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mission::mission_camera >::value();
  }
  static const char* value(const ::mission::mission_cameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mission::mission_cameraRequest> should match
// service_traits::DataType< ::mission::mission_camera >
template<>
struct DataType< ::mission::mission_cameraRequest>
{
  static const char* value()
  {
    return DataType< ::mission::mission_camera >::value();
  }
  static const char* value(const ::mission::mission_cameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mission::mission_cameraResponse> should match
// service_traits::MD5Sum< ::mission::mission_camera >
template<>
struct MD5Sum< ::mission::mission_cameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mission::mission_camera >::value();
  }
  static const char* value(const ::mission::mission_cameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mission::mission_cameraResponse> should match
// service_traits::DataType< ::mission::mission_camera >
template<>
struct DataType< ::mission::mission_cameraResponse>
{
  static const char* value()
  {
    return DataType< ::mission::mission_camera >::value();
  }
  static const char* value(const ::mission::mission_cameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MISSION_MESSAGE_MISSION_CAMERA_H
