(cl:in-package main2021-srv)
(cl:export '(MY_POS-VAL
          MY_POS
          FRIEND_POS-VAL
          FRIEND_POS
          NS-VAL
          NS
          EMERGENCY-VAL
          EMERGENCY
          TEAM-VAL
          TEAM
          TIME-VAL
          TIME
          FRIEND_ACTION-VAL
          FRIEND_ACTION
          ACTION_LIST-VAL
          ACTION_LIST
          CUP_COLOR-VAL
          CUP_COLOR
          CUP-VAL
          CUP
          HAND-VAL
          HAND
          ENEMY1_POS-VAL
          ENEMY1_POS
          ENEMY2_POS-VAL
          ENEMY2_POS
          STRATEGY-VAL
          STRATEGY
          ACTION-VAL
          ACTION
          POSITION-VAL
          POSITION
          CUP-VAL
          CUP
))